spring.application.name=w2g

# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/w2g
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

security.jwt.secret-key=0344420171215045e565e1b5eed7879d4a360c3eeb937169e7550f5adaae7812
security.jwt.expiration-time=14400000

